### ISSUE TITLE
I get an car image and battery image with text "LOADING"  

### ISSUE THREAD

**Issue by jpiatt** [usncahill/MMM-Tesla3#7]
This is an ambitious project and I hope to be able to use the module at some point in the future. At the moment however, I can't seem to get it to load completely.

This is my config entry:

```

		{
            module: 'MMM-Tesla3',
            position: 'bottom_left',       // Recommend side regions like top_left for best results
            config: {
                // See 'Configuration options' for more information.
                vehicleIndex: 0,            // default 0, index references the n+1th car returned when talking to Tesla
                showVehicleName: true, 
                refreshIntervalCharging: 5,  // 15 minutes
				showBatteryBar: true,
				showStatusIcons: true,
				batteryWidth: 125,
				batteryHeight: 30,
				carImageOptions: {
					model: "MX",
					view: "STUD_3QTR",
					options: "MDLX,WT19",
					verticalOffset: 0,
					imageOpacity: 0.4
				  },
            }
        }


```

And here's the startup log showing an error occurring in the JSON.parse call.  (At the bottom, I've displayed the version of node.js and NPM I'm using in case this is a factor.)

```
> magicmirror@2.26.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[08.03.2024 09:32.14.675] [LOG]   Starting MagicMirror: v2.26.0
[08.03.2024 09:32.14.691] [LOG]   Loading config ...
[08.03.2024 09:32.14.696] [DEBUG] config template file not exists, no envsubst
[08.03.2024 09:32.14.703] [LOG]   Loading module helpers ...
[08.03.2024 09:32.14.704] [LOG]   No helper found for module: alert.
[08.03.2024 09:32.14.718] [LOG]   Initializing new module helper ...
[08.03.2024 09:32.14.719] [LOG]   Module helper loaded: updatenotification
[08.03.2024 09:32.14.719] [LOG]   No helper found for module: clock.
[08.03.2024 09:32.14.849] [LOG]   Initializing new module helper ...
[08.03.2024 09:32.14.850] [LOG]   Module helper loaded: calendar
[08.03.2024 09:32.14.850] [LOG]   No helper found for module: weather.
[08.03.2024 09:32.15.341] [LOG]   Initializing new module helper ...
[08.03.2024 09:32.15.342] [LOG]   Module helper loaded: MMM-Jast
[08.03.2024 09:32.15.456] [LOG]   Initializing new module helper ...
[08.03.2024 09:32.15.456] [LOG]   Module helper loaded: MMM-Tesla3
[08.03.2024 09:32.15.456] [LOG]   All module helpers loaded.
[08.03.2024 09:32.15.461] [LOG]   Starting server on port 8080 ... 
[08.03.2024 09:32.15.633] [LOG]   Server started ...
[08.03.2024 09:32.15.638] [LOG]   Connecting socket for: updatenotification
[08.03.2024 09:32.15.638] [LOG]   Starting module helper: updatenotification
[08.03.2024 09:32.15.638] [LOG]   Connecting socket for: calendar
[08.03.2024 09:32.15.638] [LOG]   Starting node helper for: calendar
[08.03.2024 09:32.15.638] [LOG]   Connecting socket for: MMM-Jast
[08.03.2024 09:32.15.639] [LOG]   MMM-Jast helper method started...
[08.03.2024 09:32.15.639] [LOG]   Connecting socket for: MMM-Tesla3
[08.03.2024 09:32.15.640] [LOG]   Sockets connected & modules started ...
2024-03-08 09:32:15.932 Electron[7424:1621901] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[08.03.2024 09:32.15.934] [LOG]   Launching application.
[08.03.2024 09:32.18.392] [LOG]   Create new calendarfetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 3600000
[08.03.2024 09:32.18.449] [LOG]   Create new calendarfetcher for url: http://p39-caldav.icloud.com/published/2/MTQ0MDgyOTg0MjE0NDA4MuQ-dFWrIt6lYeNpvGnDYdIyARzN4orG5MVVMsNiQBI7bEEy8pz0EUq76REQSXq22kH3c7KIkdS1iBFulTftIOs - Interval: 3600000
[08.03.2024 09:32.18.491] [LOG]   Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL...
[08.03.2024 09:32.19.511] [INFO]  Calendar-Fetcher: Broadcasting 0 events from http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics.
[08.03.2024 09:32.19.672] [ERROR] Whoops! There was an uncaught exception...
[08.03.2024 09:32.19.673] [ERROR] TypeError: JSON.parse(...).includes is not a function
    at Request._callback (/Users/jerrypiatt/MagicMirror/modules/MMM-Tesla3/node_helper.js:155:46)
    at self.callback (/Users/jerrypiatt/MagicMirror/modules/MMM-Tesla3/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (/Users/jerrypiatt/MagicMirror/modules/MMM-Tesla3/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (/Users/jerrypiatt/MagicMirror/modules/MMM-Tesla3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.03.2024 09:32.19.673] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[08.03.2024 09:32.19.673] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[08.03.2024 09:32.19.675] [INFO]  updatenotification: Updater Class Loaded!
[08.03.2024 09:32.19.675] [INFO]  updatenotification: Checking PM2 using...
[08.03.2024 09:32.19.676] [INFO]  Checking git for module: MMM-Jast
[08.03.2024 09:32.19.707] [INFO]  updatenotification: You are not using pm2
[08.03.2024 09:32.19.796] [LOG]   Success.  Cookie expires on Sat Mar 08 2025 15:32:19 GMT-0800 (Pacific Standard Time)
[08.03.2024 09:32.19.856] [INFO]  Checking git for module: MMM-Tesla3
[08.03.2024 09:32.19.925] [INFO]  Checking git for module: MagicMirror
[08.03.2024 09:32.21.649] [INFO]  Calendar-Fetcher: Broadcasting 6 events from http://p39-caldav.icloud.com/published/2/MTQ0MDgyOTg0MjE0NDA4MuQ-dFWrIt6lYeNpvGnDYdIyARzN4orG5MVVMsNiQBI7bEEy8pz0EUq76REQSXq22kH3c7KIkdS1iBFulTftIOs.
[08.03.2024 09:32.22.376] [WARN]  API request for .DJI failed: Quote not found for ticker symbol: .DJI
[08.03.2024 09:32.41.584] [LOG]   Shutting down server...
[08.03.2024 09:32.41.584] [LOG]   Stopping module helper: updatenotification
[08.03.2024 09:32.41.585] [LOG]   Stopping module helper: calendar
[08.03.2024 09:32.41.585] [LOG]   Stopping module helper: MMM-Jast
[08.03.2024 09:32.41.585] [LOG]   Stopping module helper: MMM-Tesla3
[08.03.2024 09:32.41.585] [LOG]   Node_helpers stopped ...
jerrypiatt@Mac-Daddy MagicMirror % node --version
v18.12.1
jerrypiatt@Mac-Daddy MagicMirror % npm --version
8.19.2
jerrypiatt@Mac-Daddy MagicMirror % npm start     
```

**Comment by elevins** [comment]
+1 for same issue

**Comment by usncahill** [comment]
Closed as not fixable. See #5. Sorry, I tried.
